### ISSUE TITLE
USER STORY: 

### ISSUE THREAD

**Issue by MiswaQ** [MiswaQ/My-First-Agile-Project#5]
As a **voter** I can **stay anonymous** so that **my name would not be known**

### Acceptance criteria

* A place for a check box to stay anonymous.
* The option should be checked default.
* The check box should be next to submit button. 
* The user should be prompted to add name. If the checkbox is unchecked.

### Tasks

- [ ] Add a checkbox that's checked default using HTML and CSS.
- [ ] Add somewhere to put the name if checkbox unchecked.
- [ ] Test the script.
- [ ] Test the functionality.
